/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useContext } from 'react';
import { useGLTF } from '@react-three/drei';
import GUIContext from 'GUIContext';
import objectPath from 'object-path';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/TextBox.glb');
  const { data } = useContext(GUIContext);
  let { messageBoxColour } = objectPath.get(data, 'scene.messageQueue');

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh castShadow receiveShadow geometry={nodes['Message-Box'].geometry} material={materials['Blue Emission']}>
          <meshStandardMaterial color={messageBoxColour} toneMapped={false} />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes['Message-Box_1'].geometry} material={materials['Material.001']}>
          <meshStandardMaterial color={messageBoxColour} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/TextBox.glb');
